name: build-env
channels:
  - conda-forge
dependencies:
  - jupyterlite-xeus>=2.0.0,<3
  - voici_core>=0.7,<0.8
  - voici
  - xeus-python=0.17.2  # Specific version
  - ipywidgets=8.1.1    # Specific version
  - widgetsnbextension=4.0.9
  - jupyterlab_widgets=3.0.9